// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// mixbox_blend
IntegerVector mixbox_blend(unsigned char r1, unsigned char g1, unsigned char b1, unsigned char r2, unsigned char g2, unsigned char b2, float t);
RcppExport SEXP _sosMixboxRcpp_mixbox_blend(SEXP r1SEXP, SEXP g1SEXP, SEXP b1SEXP, SEXP r2SEXP, SEXP g2SEXP, SEXP b2SEXP, SEXP tSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< unsigned char >::type r1(r1SEXP);
    Rcpp::traits::input_parameter< unsigned char >::type g1(g1SEXP);
    Rcpp::traits::input_parameter< unsigned char >::type b1(b1SEXP);
    Rcpp::traits::input_parameter< unsigned char >::type r2(r2SEXP);
    Rcpp::traits::input_parameter< unsigned char >::type g2(g2SEXP);
    Rcpp::traits::input_parameter< unsigned char >::type b2(b2SEXP);
    Rcpp::traits::input_parameter< float >::type t(tSEXP);
    rcpp_result_gen = Rcpp::wrap(mixbox_blend(r1, g1, b1, r2, g2, b2, t));
    return rcpp_result_gen;
END_RCPP
}
// get_colors_to_mix
NumericVector get_colors_to_mix(double x, NumericVector values);
RcppExport SEXP _sosMixboxRcpp_get_colors_to_mix(SEXP xSEXP, SEXP valuesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type values(valuesSEXP);
    rcpp_result_gen = Rcpp::wrap(get_colors_to_mix(x, values));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_sosMixboxRcpp_mixbox_blend", (DL_FUNC) &_sosMixboxRcpp_mixbox_blend, 7},
    {"_sosMixboxRcpp_get_colors_to_mix", (DL_FUNC) &_sosMixboxRcpp_get_colors_to_mix, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_sosMixboxRcpp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
